---
- hosts: all
  sudo: true
  gather_facts: true
  vars:
    mysql_root_password: 1Mn8iehsy67!42p
    user_gui_password: $6$Zz7q20uyuUF$saXA3Lu/04kWSbRRW/RDIpE9BTmdD2qiI.rm2vvDxS6Ez.917n7.IiSU/nhCm5fj5vaJ1Y3S3coS5LooCwYfB1 #password=dev
  tasks:
    - debug: var=inventory_hostname
    - debug: var=ansible_hostname
    - debug: var=hostvars


    - name: "Updating repositories"
      apt:
        update_cache: yes
    - name: "Upgrading packages"
      apt:
        upgrade: dist
    - name: "Removing no longer required dependencies"
      apt:
        autoremove: yes
 
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      sudo: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: Create a login user
      user:
        name: devuser
        password: "{{user_gui_password}}"
        groups:
          - sudo
          - root
        state: present
        shell: /bin/bash
        system: yes
        createhome: yes
        home: /home/devuser
    #install mysql
    - name: Install MySQL and MySQL Workbench
      apt: name={{item}} update_cache=yes cache_valid_time=3600 state=present
      sudo: yes
      with_items:
        - python-mysqldb
        - mysql-server
        - mysql-workbench
    #- name: copy cnf
    #  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
    #  sudo: yes
    - name: Start the MySQL service
      sudo: yes
      service: 
        name: mysql 
        state: started
        enabled: true
    - name: update mysql root password for all root accounts
      sudo: yes
      mysql_user: 
        name: root 
        host: "{{item}}" 
        password: "{{mysql_root_password}}"
        login_user: root
        login_password: "{{mysql_root_password}}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ansible_hostname}}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Install Apache2, git
      become: yes
      apt: name={{item}} update_cache=yes state=latest 
      with_items: 
        - apache2
        - git
    #install Spring STS

    #http://download.springsource.com/release/STS4/4.1.1.RELEASE/dist/e4.10/spring-tool-suite-4-4.1.1.RELEASE-e4.10.0-linux.gtk.x86_64.tar.gz

    # - name: Download Sprinf Tool Suite 
    #   get_url:
    #     url: http://download.springsource.com/release/STS4/4.1.1.RELEASE/dist/e4.10/spring-tool-suite-4-4.1.1.RELEASE-e4.10.0-linux.gtk.x86_64.tar.gz
    #     dest: /etc/STS-installer.tar.gz
    #     mode: 0640

    # - file:
    #     path: /etc/STS-installer.tar.gz
    #     owner: devuser
    #     group: root
    #     # when specifying mode using octal numbers, add a leading 0
    #     mode: 0001

    # - name: unzip tar.gz
    #   become: yes
    #   shell: tar -xvzf  /etc/STS-installer.tar.gz -C /etc

    - name: download and unarchive STS
      unarchive:
        src: http://download.springsource.com/release/STS4/4.1.1.RELEASE/dist/e4.10/spring-tool-suite-4-4.1.1.RELEASE-e4.10.0-linux.gtk.x86_64.tar.gz
        dest: /etc
        remote_src: yes

    - lineinfile:
        path: "/etc/sts-4.1.1.RELEASE/configuration/config.ini"
        regexp: '^osgi.instance.area.default='
        line: 'osgi.instance.area.default=/home/devuser/workspace'

    - name: Fix sts permissions
      become: yes
      file: dest=/etc/sts-4.1.1.RELEASE owner=root group=root mode=u=rwX,g=rX,o=rX recurse=yes

    # - name: copy launcher for STS to desktop
    #   copy:
    #     src: /etc/sts-4.1.1.RELEASE/SpringToolSuite4
    #     dest: /home/devuser/Desktop

    - name: chenge kerboard
      become: yes
      shell: loadkeys fr







#         modified:   p2/org.eclipse.equinox.p2.engine/profileRegistry/DefaultProfile.profile/.data/.settings/org.eclipse.equinox.p2.artifact.repository.prefs
#   modified:   p2/org.eclipse.equinox.p2.engine/profileRegistry/DefaultProfile.profile/.data/.settings/org.eclipse.equinox.p2.metadata.repository.prefs

# Untracked files:
#   (use "git add <file>..." to include in what will be committed)

#   configuration/.settings/
#   configuration/org.eclipse.core.runtime/
#   configuration/org.eclipse.equinox.app/
#   configuration/org.eclipse.osgi/
#   p2/org.eclipse.equinox.p2.engine/profileRegistry/DefaultProfile.profile/.data/.settings/org.eclipse.equinox.p2.ui.sdk.scheduler.prefs
#   p2/org.eclipse.equinox.p2.engine/profileRegistry/DefaultProfile.profile/1549629215994.profile.gz
#   p2/org.eclipse.equinox.p2.engine/profileRegistry/DefaultProfile.profile/1549629216589.profile.gz

