---
- hosts: all
  sudo: true
  gather_facts: true
  vars:
    user_gui_password: $6$Zz7q20uyuUF$saXA3Lu/04kWSbRRW/RDIpE9BTmdD2qiI.rm2vvDxS6Ez.917n7.IiSU/nhCm5fj5vaJ1Y3S3coS5LooCwYfB1 #password=dev
    jenkins_home: '/var/lib/jenkins'
  tasks:
    - name: "Updating repositories"
      apt:
        update_cache: yes
    - name: "Upgrading packages"
      apt:
        upgrade: dist
    - name: "Removing no longer required dependencies"
      apt:
        autoremove: yes
 
    - name: Install add-apt-repostory
      become: yes
      apt: name=software-properties-common state=latest

    - name: Add Oracle Java Repository
      become: yes
      apt_repository: repo='ppa:webupd8team/java'

    - name: Accept Java 8 License
      become: yes
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

    - name: Install Oracle Java 8
      become: yes
      sudo: yes
      apt: name={{item}} state=latest
      with_items:
        - oracle-java8-installer
        - ca-certificates
        - oracle-java8-set-default

    - name: Create a login user
      user:
        name: devuser
        password: "{{user_gui_password}}"
        groups:
          - sudo
          - root
        state: present
        shell: /bin/bash
        system: yes
        createhome: yes
        home: /home/devuser
    
    - name: chenge kerboard
      become: yes
      shell: loadkeys fr

    # - name: download jenkins
    #   become: yes
    #   shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -


    - name: Add an Apt signing key jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: add jenkins to repository
      become: yes
      shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
    
    - name: "Updating repositories"
      apt:
        update_cache: yes
    - name: "Upgrading packages"
      apt:
        upgrade: dist

    - name: Install jenkins, Git
      become: yes
      apt: name={{item}} update_cache=yes state=latest 
      with_items:
        - jenkins
        - git

    - name: start service httpd jenkins
      service:
        name: jenkins
        state: started

    - name: Wait Buffer
      wait_for: timeout=50

    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: print init password jenkins
      debug:
        var: result.stdout